### ISSUE TITLE
Add jobs that compile using C++11

### ISSUE THREAD

**Issue by ralphlange** [epics-base/jenkins-jobs#14]
Michael started evaluating if V4 compiles using the C++11 standard.

As the CloudBees builders use gcc4.7, it would be possible and worthwhile to have a set of jobs (off master) compiling with `-std=c++11`.
No artifacts, no uploads, just compiling.

**Comment by mdavidsaver** [comment]
I think this is a reasonable way to start.

There are of course a lot of places to add this options.  FYI I added

```
OP_SYS_CXXFLAGS += -std=c++11
```

to 'configure/os/CONFIG_SITE.Common.linux-x86' and 'configure/os/CONFIG_SITE.Common.linux-x86_64'.  This is to avoid setting it for the older rtems cross compiler I still use (gcc 4.3).
