### ISSUE TITLE
Java: Artifact archiving must be able to find jars in submodules

### ISSUE THREAD

**Issue by ralphlange** [epics-base/jenkins-jobs#15]
Reported by @mrkraimer:

Building PR epics-base/exampleJava#3 on CloudBees [failed](https://openepics.ci.cloudbees.com/job/example%20%28Java%29%20-%20PullRequests/1/) with:

```
...
Archiving artifacts
ERROR: No artifacts found that match the file pattern "target/.jar". Configuration error?
ERROR: ‘target/.jar’ doesn’t match anything, but ‘database/target/*.jar’ does. Perhaps that’s what you mean?
Build step 'Archive the artifacts' changed build result to FAILURE
```

This repo has submodules. The jenkins job should find artifacts in submodules when archiving the artifacts.

**Comment by mrkraimer** [comment]
On 03/18/2016 06:02 AM, Ralph Lange wrote:

> Closed #15 https://github.com/epics-base/jenkins-jobs/issues/15 via 
> e98bb7e 
> https://github.com/epics-base/jenkins-jobs/commit/e98bb7ede36b477ba1ec4e10561838542e821466.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/epics-base/jenkins-jobs/issues/15#event-594644058

Thanks!!

I see that All checks have passed in

https://github.com/epics-base/exampleJava/pull/3

Marty
