### ISSUE TITLE
Create release/0.5 job for pvaPy

### ISSUE THREAD

**Issue by anjohnson** [epics-base/jenkins-jobs#8]
I created the release/0.5 branch in pvaPy, but we will need to modify the jenkins/cloudbees_\* scripts as the upstream branch jobs are created, since all the wget URLs in them need to be pointed to their respective Release-x.y jobs. I already prepared the scripts on the branch for this, just set the new *_BRANCH variables to match as the upstream branches become available. I can't tag this branch until that process is complete.

**Comment by ralphlange** [comment]
Nice way to simplify configuration of the dependant releases - adopted it for pvAccessCPP.
